import {LoadingSkeleton} from './loading-skeleton';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Search,Download,RefreshCw,History,ChevronDown} from 'lucide-react';
import {api} from '../lib/http';
import {downloadBlob} from '../lib/media-tools';
import {dateLabel,type LocalRoom} from '../lib/model';
import {AUDIT_CATEGORIES,AUDIT_ACTIONS,auditChanges,auditCsv,auditContext,type AuditEntry} from '../lib/audit';

export function AuditPanel({rooms}:{rooms:LocalRoom[]}){
 const roomNames=Object.fromEntries(rooms.map(room=>[room.id,room.site+' / '+room.name]));
 const [entries,setEntries]=useState<AuditEntry[]>([]),[category,setCategory]=useState(''),[search,setSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const generation=useRef(0),parameters=useRef('');
 const query=useCallback(()=>{const params=new URLSearchParams();if(category)params.set('category',category);if(search.trim())params.set('search',search.trim());if(from)params.set('from',new Date(from+'T00:00:00').toISOString());if(to)params.set('to',new Date(to+'T23:59:59.999').toISOString());return params;},[category,search,from,to]);
 async function fetchPage(params:URLSearchParams){return api<{entries:AuditEntry[];nextCursor:string|null}>('audit?'+params);}
 const load=useCallback(async()=>{const run=++generation.current;setBusy(true);setError('');try{const params=query();parameters.current=params.toString();const result=await api<{entries:AuditEntry[];nextCursor:string|null}>('audit?'+params);if(run===generation.current){setEntries(result.entries);setCursor(result.nextCursor);}}catch(e){if(run===generation.current)setError((e as Error).message);}finally{if(run===generation.current)setBusy(false);}},[query]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),300);return()=>{clearTimeout(timer);generation.current++;};},[load]);
 return <main className="workspace audit-workspace"><div className="section-heading"><div><p className="eyebrow">REGISTRO GENERAL DEL EVENTO</p><h1>Auditoría</h1><p className="subtle">Quién cambió qué y cuándo. Los registros guardados se conservan.</p></div><button className="button secondary" disabled={busy} onClick={()=>void load()}><RefreshCw size={22}/>Actualizar</button></div>
 <section className="panel"><div className="audit-filters"><label className="search-field"><Search size={22}/><input aria-label="Buscar en auditoría" maxLength={120} placeholder="Persona o nombre del registro" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="field"><span>Qué quieres revisar</span><select aria-label="Categoría de auditoría" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todo el evento</option>{Object.entries(AUDIT_CATEGORIES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="field"><span>Desde</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field"><span>Hasta</span><input type="date" min={from||undefined} value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="actions"><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const params=query();const records:AuditEntry[]=[];let next:string|null=null;do{if(next)params.set('before',next);const result=await fetchPage(params);records.push(...result.entries);next=result.nextCursor;if(records.length>=10000&&next)throw new Error('Hay más de 10.000 cambios. Acota las fechas para descargar el registro.');}while(next);downloadBlob(new Blob([auditCsv(records,roomNames)],{type:'text/csv;charset=utf-8'}),'OrdenColegio-auditoria.csv');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Download size={22}/>Descargar auditoría</button><span className="subtle">{entries.length} cambios mostrados{cursor?' · hay más':''}</span></div><p className="fine-print">Se registran los cambios respaldados. Los pendientes sin señal aparecerán al sincronizar. De antes de esta actualización se conserva el historial disponible de los espacios.</p></section>
 {error&&<p className="auth-error" role="alert">{error}</p>}{busy&&!entries.length&&<LoadingSkeleton kind="history" label="Cargando auditoría…"/>}
 <div className="audit-list">{entries.map(entry=><details className="panel audit-entry" key={entry.id}><summary><History size={24}/><div><strong>{entry.entity_name}</strong><p>{AUDIT_ACTIONS[entry.action]??entry.action} · {AUDIT_CATEGORIES[entry.category]??entry.category}</p>{entry.category==='files'&&<span>{auditContext(entry,roomNames).room} · {auditContext(entry,roomNames).phase}</span>}<span>{entry.actor_name} · {dateLabel(entry.created_at)}</span>{entry.legacy&&<small>Del historial anterior</small>}</div><ChevronDown size={24}/></summary><dl className="audit-diff">{auditChanges(entry).map(change=><div key={change.field}><dt>{change.field}</dt><dd><span>Antes: {change.before}</span><strong>Después: {change.after}</strong></dd></div>)}</dl>{auditChanges(entry).length===0&&<p className="subtle spaced">Acción registrada sin cambios de contenido.</p>}</details>)}</div>
 {!busy&&!entries.length&&!error&&<div className="empty-state"><History size={36}/><h2>No hay cambios con estos filtros</h2></div>}
 {cursor&&<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');const run=generation.current;try{const params=new URLSearchParams(parameters.current);params.set('before',cursor);const result=await fetchPage(params);if(run===generation.current){setEntries(previous=>[...previous,...result.entries]);setCursor(result.nextCursor);}}catch(e){setError((e as Error).message);}finally{if(run===generation.current)setBusy(false);}}}>Ver más cambios</button>}
 </main>;
}
