import {useEffect,useState} from 'react';
import {ArrowRight,Copy,UserPlus,LogOut} from 'lucide-react';
import {api} from '../lib/sync';
import type {User} from '../lib/model';
export function AuthPanel(){
 const fragment=new URLSearchParams(location.hash.slice(1));
 const [mode,setMode]=useState<'login'|'setup'|'join'>(fragment.has('invite')?'join':'login');
 const [key,setKey]=useState(fragment.get('setup')||fragment.get('invite')||'');
 const [name,setName]=useState('');const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{void api<{needsSetup:boolean}>('auth/status').then(s=>{if(s.needsSetup)setMode('setup');}).catch(e=>setError(e.message));if(location.hash)history.replaceState(null,'',location.pathname);},[]);
 return <section className="panel auth-panel"><p className="eyebrow">{mode==='setup'?'PRIMER INGRESO':mode==='join'?'ACCESO DEL EQUIPO':'TU REGISTRO'}</p><h2>{mode==='setup'?'Crea tu acceso de coordinador':mode==='join'?'Únete al equipo':'Entrar a Orden Colegio'}</h2><p className="subtle">{mode==='setup'?'Elige el usuario y la contraseña que usarás en tus dispositivos.':mode==='join'?'Tu acceso es personal. Los registros del evento se comparten con el equipo.':'Usa tu usuario y contraseña del evento.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('auth/'+mode,{name,username,password,...(mode==='setup'?{setupKey:key}:mode==='join'?{code:key}:{})});location.reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {mode!=='login'&&<label className="field"><span>Tu nombre</span><input required minLength={2} maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}
 {mode!=='login'&&<label className="field"><span>{mode==='setup'?'Clave de instalación':'Código de invitación'}</span><input required type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label>}
 <label className="field"><span>Usuario</span><input required minLength={3} maxLength={40} pattern="[a-zA-Z0-9._-]+" autoCapitalize="none" autoCorrect="off" autoComplete="username" placeholder="Ej.: lucas" value={username} onChange={e=>setUsername(e.target.value)}/></label>
 <label className="field"><span>Contraseña{mode!=='login'?' · mínimo 12 caracteres':''}</span><input required type="password" minLength={mode==='login'?1:12} maxLength={200} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>
 {error&&<p className="auth-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Entrando…':mode==='login'?'Entrar':'Crear mi acceso'}<ArrowRight size={17}/></button></form>
 {mode!=='setup'&&<button className="text-button spaced" onClick={()=>{setMode(mode==='login'?'join':'login');setError('');}}>{mode==='login'?'Tengo un código de invitación':'Ya tengo usuario'}</button>}
 </section>;
}
export function TeamAccess({user,team,pending,onChange}:{user:User,team:User[],pending:number,onChange:()=>Promise<void>}){
 const [name,setName]=useState('');const [link,setLink]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 return <><p className="subtle">Conectado como {user.name}</p>{team.map(m=><div className="member-row" key={m.id}><span className="avatar">{m.name.slice(0,1).toUpperCase()}</span><div><strong>{m.name}</strong><p>{m.role==='coordinator'?'Coordinador':'Encargado'} · {m.email}</p></div>{user.role==='coordinator'&&m.id!==user.id&&<button className="text-button" onClick={async()=>{if(!window.confirm('¿Quitar el acceso de '+m.name+'? Sus registros se conservarán.'))return;try{await api('auth/revoke',{userId:m.id});await onChange();}catch(e){setMessage((e as Error).message);}}}>Quitar acceso</button>}</div>)}
 {user.role==='coordinator'&&<form className="spaced" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const result=await api<{code:string}>('auth/invites',{name});setLink(location.origin+'/#invite='+result.code);setMessage('Válido por 48 horas y para una sola persona.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><label className="field"><span>Invitar a un encargado</span><input required minLength={2} maxLength={100} placeholder="Nombre del encargado" value={name} onChange={e=>setName(e.target.value)}/></label><button className="button secondary" disabled={busy}><UserPlus size={17}/>Crear enlace de acceso</button></form>}
 {link&&<div className="invite-result"><label className="field"><span>Enlace para compartir</span><input readOnly value={link} onFocus={e=>e.target.select()}/></label><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Enlace copiado.');}catch{setMessage('Selecciona y copia el enlace.');}}}><Copy size={16}/>Copiar enlace</button></div>}{message&&<p role="status" className="fine-print">{message}</p>}
 <button className="text-button spaced" disabled={pending>0} onClick={async()=>{try{await api('auth/logout',{});localStorage.removeItem('orden-last-user');location.reload();}catch(e){setMessage((e as Error).message);}}}><LogOut size={16}/>Cerrar sesión</button>{pending>0&&<p className="fine-print">Respalda los pendientes antes de cerrar sesión.</p>}</>;
}
