import {Check,ChevronDown,AlertTriangle} from 'lucide-react';
import {type LocalRoom,type Phase} from '../lib/model';
import {toggleCondition} from '../lib/inspection';

export function ConditionPanel({room,phase,onChange}:{room:LocalRoom;phase:Phase;onChange:(room:LocalRoom)=>void}){
 const stage=room[phase],checks=Object.entries(stage.checks),done=checks.filter(([,v])=>v!=='pending').length,issues=checks.filter(([,v])=>v==='issue').length;
 return <section className="panel condition-panel"><details key={room.id+phase} className="condition-fold"><summary><div><h2>Estado del espacio</h2><span className="subtle">{done} de {checks.length} revisados{issues?' · '+issues+' con observaciones':''}</span></div><ChevronDown className="fold-chevron" size={26}/></summary><p className="fine-print">Toca una opción. Si la tocas otra vez, queda sin revisar.</p><div className="check-list">{checks.map(([name,value])=><div className="check-row" key={name}><span>{name}</span><div className="condition-options" role="group" aria-label={name}>{([{value:'ok',label:'Bien'},{value:'issue',label:'Observación'},{value:'na',label:'No aplica'}] as const).map(option=><button type="button" key={option.value} disabled={!!stage.confirmedAt} aria-pressed={value===option.value} className={value===option.value?'selected '+option.value:''} onClick={()=>onChange(toggleCondition(room,phase,name,option.value))}>{value===option.value&&(option.value==='issue'?<AlertTriangle size={20}/>:<Check size={20}/>)}{option.label}</button>)}</div></div>)}</div></details>
 <label className="field"><span>Observaciones</span><textarea aria-label="Observaciones" placeholder="Daños previos, detalles o cambios que deban quedar registrados." readOnly={!!stage.confirmedAt} value={stage.notes} onChange={e=>onChange({...room,[phase]:{...stage,notes:e.target.value}})}/></label>{phase==='return'&&room.reception.notes&&<div className="reception-note"><strong>Al recibir</strong><p>{room.reception.notes}</p></div>}</section>;
}
