import {useState} from 'react';
import {Plus,Pencil,Copy,Trash2,Check,ChevronDown} from 'lucide-react';
import {type LocalRoom,type Phase} from '../lib/model';
import {addInventoryItem,renameInventoryItem,removeInventoryItem,duplicateInventoryItem,copyInventoryNames} from '../lib/inspection';
import {toast} from 'sonner';

export function InventoryPanel({room,phase,rooms,onChange,readOnly=false}:{readOnly?:boolean;room:LocalRoom;phase:Phase;rooms:LocalRoom[];onChange:(room:LocalRoom)=>Promise<void>}){
 const [editing,setEditing]=useState(false),[name,setName]=useState(''),[renaming,setRenaming]=useState<string|null>(null),[newName,setNewName]=useState(''),[sourceId,setSourceId]=useState(''),[busy,setBusy]=useState(false);
 const locked=readOnly||!!room[phase].confirmedAt;
 async function change(fn:()=>LocalRoom,structural=false){if(readOnly)return false;setBusy(true);try{await onChange(fn());if(structural&&(room.reception.confirmedAt||room.return.confirmedAt))toast.info('Inventario actualizado. Revisa y confirma nuevamente.');return true;}catch(e){toast.error((e as Error).message);return false;}finally{setBusy(false);}}
 return <section className={'panel inventory-panel'+(readOnly?' read-only-panel':'')}><div className="panel-title"><h2>Inventario</h2>{!readOnly&&<button className="button secondary" aria-expanded={editing} onClick={()=>setEditing(!editing)}><Pencil size={22}/>{editing?'Cerrar edición':'Editar inventario'}</button>}</div>
 {editing&&!readOnly&&!readOnly&&<div className="inventory-tools"><p className="subtle">Añade, cambia nombres o copia elementos. Las copias quedan sin cantidades para contarlas en este espacio.</p><form className="inline-item-form" onSubmit={async e=>{e.preventDefault();if(await change(()=>addInventoryItem(room,name),true))setName('');}}><label className="field"><span>Nuevo elemento</span><input aria-label="Nuevo elemento" placeholder="Ej.: estantes" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><button className="button primary" disabled={busy}><Plus size={22}/>Agregar</button></form>
 <details className="compact-tools"><summary><Copy size={22}/>Copiar de otro espacio<ChevronDown size={20}/></summary><label className="field"><span>Espacio de origen</span><select value={sourceId} onChange={e=>setSourceId(e.target.value)} aria-label="Espacio de origen"><option value="">Selecciona un espacio</option>{rooms.filter(r=>r.id!==room.id&&!r.archived).map(r=><option key={r.id} value={r.id}>{r.site} / {r.name}</option>)}</select></label><button className="button secondary spaced" disabled={busy||!sourceId} onClick={()=>{const source=rooms.find(r=>r.id===sourceId);if(source)void change(()=>copyInventoryNames(room,source),true);}}>Copiar nombres que faltan</button></details></div>}
 <div className="inventory-list">{room.items.map(item=><div className="inventory-entry" key={item.id}><div className="inventory-row"><div><label htmlFor={'count-'+item.id}>{item.name}</label>{phase==='return'&&<span className="subtle">Al recibir: {item.reception??'Sin registrar'}</span>}</div><div className="counter"><button aria-label={'Restar '+item.name} disabled={locked||busy} onClick={()=>void change(()=>({...room,items:room.items.map(i=>i.id===item.id?{...i,[phase]:Math.max(0,(i[phase]??0)-1)}:i)}))}>−</button><input id={'count-'+item.id} aria-label={item.name} type="number" min={0} max={1000000} step={1} inputMode="numeric" placeholder="—" readOnly={locked} value={item[phase]??''} onChange={e=>{const n=e.target.value===''?null:Number(e.target.value);if(n!==null&&(!Number.isInteger(n)||n<0||n>1000000))return;void change(()=>({...room,items:room.items.map(i=>i.id===item.id?{...i,[phase]:n}:i)}));}}/><button aria-label={'Sumar '+item.name} disabled={locked||busy} onClick={()=>void change(()=>({...room,items:room.items.map(i=>i.id===item.id?{...i,[phase]:Math.min(1000000,(i[phase]??0)+1)}:i)}))}>+</button></div>{phase==='return'&&item.reception!==null&&item.return!==null&&item.return!==item.reception&&<span className="difference">{item.return-item.reception>0?'+':''}{item.return-item.reception}</span>}</div>
 {editing&&<div className="inventory-item-tools">{renaming===item.id?<form onSubmit={async e=>{e.preventDefault();if(await change(()=>renameInventoryItem(room,item.id,newName),true))setRenaming(null);}}><label className="field"><span>Nombre del elemento</span><input aria-label={'Nuevo nombre de '+item.name} autoFocus required maxLength={100} value={newName} onChange={e=>setNewName(e.target.value)}/></label><div className="actions"><button className="button primary" disabled={busy}><Check size={20}/>Guardar nombre</button><button className="button secondary" type="button" onClick={()=>setRenaming(null)}>Cancelar</button></div></form>:<div className="actions"><button className="button secondary" onClick={()=>{setRenaming(item.id);setNewName(item.name);}} aria-label={'Renombrar '+item.name}><Pencil size={20}/>Renombrar</button><button className="button secondary" disabled={busy} onClick={()=>void change(()=>duplicateInventoryItem(room,item.id),true)} aria-label={'Copiar '+item.name}><Copy size={20}/>Copiar</button><button className="button secondary danger-button" disabled={busy} aria-label={'Quitar '+item.name} onClick={()=>{if(window.confirm('¿Quitar “'+item.name+'” y sus cantidades de este espacio?'))void change(()=>removeInventoryItem(room,item.id),true);}}><Trash2 size={20}/>Quitar</button></div>}</div>}</div>)}</div>
 {!room.items.length&&<p className="subtle spaced">No hay elementos. Abre «Editar inventario» para agregarlos.</p>}
 <p className="fine-print">Vacío: sin contar. Cero: se revisó y no había unidades.{locked&&!readOnly?' Para cambiar cantidades, pulsa «Editar esta recepción» o «Editar esta devolución».':''}</p></section>;
}
