import {useEffect,useRef,useState} from 'react';
import {Download,Printer,Check,ChevronDown} from 'lucide-react';
import {toast} from 'sonner';
import {LoadingSkeleton} from './loading-skeleton';
import {getMeta,setMeta} from '../lib/local-store';
import {downloadBlob} from '../lib/media-tools';
import type {LocalRoom,Room} from '../lib/model';
import {DEFAULT_LABEL_OPTIONS,LABEL_SIZES,MAX_LABELS,labelLayout,labelText,printableLabels,type LabelOptions,type LabelBatch,type LabelSize} from '../lib/labels';
import './labels.css';

type PrintPrefs={options:LabelOptions;selected:string[];quantities:Record<string,number>};
const printItems=(room:LocalRoom)=>room.items.length?room.items:[{id:'label-only',name:'Papeles',reception:1}];
export function LabelsPage({rooms,scope='all',readOnly=false,onSave}:{rooms:LocalRoom[];scope?:string;readOnly?:boolean;onSave:(room:Room)=>Promise<unknown>}){
 const [options,setOptions]=useState<LabelOptions>(DEFAULT_LABEL_OPTIONS),[selected,setSelected]=useState<string[]>([]),[quantities,setQuantities]=useState<Record<string,number>>({}),[drafts,setDrafts]=useState<Record<string,string>>({}),[search,setSearch]=useState('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;getMeta<PrintPrefs>('label-print-preferences').then(saved=>{if(!active)return;if(saved){setOptions({...DEFAULT_LABEL_OPTIONS,...saved.options});setQuantities(saved.quantities??{});}setSelected(scope!=='all'?[scope]:(saved?.selected??[]));}).catch(()=>{if(active)setSelected(scope!=='all'?[scope]:[]);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[scope]);
 useEffect(()=>{if(loading)return;const timer=setTimeout(()=>{void setMeta('label-print-preferences',{options,selected,quantities}).catch(()=>setError('No se pudo guardar la configuración en este teléfono.'));},250);return()=>clearTimeout(timer);},[options,selected,quantities,loading]);
 const selectedRooms=rooms.filter(r=>selected.includes(r.id));
 const amount=(room:LocalRoom,itemId:string)=>quantities[room.id+':'+itemId]??printItems(room).find(i=>i.id===itemId)?.reception??0;
 const batches:LabelBatch[]=selectedRooms.flatMap(room=>printItems(room).map(item=>({roomId:room.id,text:drafts[room.id]??labelText(room),item:room.items.length?item.name:'',quantity:amount(room,item.id)}))).filter(b=>b.quantity>0);
 const total=batches.reduce((n,b)=>n+b.quantity,0),layout=labelLayout(options),pages=Math.ceil(total/layout.perPage);
 let validation='';try{if(total)printableLabels(batches,options);}catch(e){validation=e instanceof Error?e.message:'Revisa las cantidades.';}
 const first=batches[0];const previewText=first?[first.text,options.includeItem?first.item:'',options.numbered?'01':''].filter(Boolean).join('\n'):selectedRooms[0]?(drafts[selectedRooms[0].id]??labelText(selectedRooms[0])):'Sala 1';
 const preview=useRef<HTMLDivElement>(null),previewContent=useRef<HTMLSpanElement>(null);
 useEffect(()=>{const box=preview.current,content=previewContent.current;if(!box||!content)return;let font=options.fontSize;content.style.fontSize=font+'pt';while(font>8&&(content.scrollHeight>box.clientHeight-16||content.scrollWidth>box.clientWidth-16)){font-=.5;content.style.fontSize=font+'pt';}},[previewText,options.fontSize,options.size,loading]);
 const matches=(room:LocalRoom)=>(room.name+' '+room.site).toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es'));
 const toggle=(id:string)=>setSelected(previous=>previous.includes(id)?previous.filter(v=>v!==id):[...previous,id]);
 async function saveText(room:LocalRoom){const text=(drafts[room.id]??labelText(room)).trim();if(!text)return setError('Escribe el texto de la etiqueta.');setBusy(room.id);setError('');try{await onSave({...room,labelText:text===room.name?'':text});setDrafts(previous=>{const next={...previous};delete next[room.id];return next;});toast.success('Texto guardado con el espacio.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el texto.');}finally{setBusy('');}}
 async function generate(print:boolean){
  if(!total||validation||busy)return;let printWindow:Window|null=null;
  if(print){printWindow=window.open('','_blank');if(!printWindow){setError('El navegador bloqueó la ventana. Permite abrirla o descarga el PDF para imprimir.');return;}printWindow.document.title='Preparando etiquetas';printWindow.document.body.textContent='Preparando tus etiquetas…';printWindow.opener=null;}
  setBusy(print?'print':'pdf');setError('');
  try{await setMeta('label-print-preferences',{options,selected,quantities});const {createLabelsDocument,labelsPrintHtml}=await import('../lib/label-pdf');const document=await createLabelsDocument(batches,options);
   if(print&&printWindow&&!printWindow.closed){printWindow.document.open();printWindow.document.write(labelsPrintHtml(document,options));printWindow.document.close();printWindow.focus();printWindow.print();}else if(!print)downloadBlob(document.blob,'Etiquetas-'+(selectedRooms.length===1?selectedRooms[0].name.replace(/[^a-zA-Z0-9áéíóúñÁÉÍÓÚÑ_-]/g,'-'):'espacios')+'.pdf');
  }catch(e){printWindow?.close();setError(e instanceof Error?e.message:'No se pudieron preparar las etiquetas.');}finally{setBusy('');}
 }
 if(loading)return <main className="workspace"><h1>Etiquetas</h1><LoadingSkeleton kind="list" label="Preparando etiquetas…"/></main>;
 return <main className="workspace labels-page"><div className="section-heading"><div><p className="eyebrow">PAPELES PARA EL MOBILIARIO</p><h1>Etiquetas</h1><p className="subtle">Elige el espacio y cuántos papeles necesitas pegar.</p></div></div>
  <div className="labels-layout"><div className="labels-editor"><section className="panel"><div className="panel-title"><h2>Espacios</h2><span>{selectedRooms.length} seleccionados</span></div><label className="field"><span>Buscar espacio</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sala, biblioteca…"/></label><div className="labels-selection-actions"><button className="text-button" onClick={()=>setSelected(rooms.map(r=>r.id))}>Seleccionar todos</button><button className="text-button" onClick={()=>setSelected([])}>Quitar selección</button></div>
   <div className={'label-room-list'+(!selectedRooms.length?' empty-selection':'')}>{rooms.filter(r=>matches(r)&&(!selectedRooms.length||selected.includes(r.id))).map(room=>{
    const checked=selected.includes(room.id),text=drafts[room.id]??labelText(room),changed=text.trim()!==labelText(room);
    return <section className={'label-room'+(checked?' selected':'')} key={room.id}><label className="label-room-choice"><input type="checkbox" checked={checked} onChange={()=>toggle(room.id)}/><span><strong>{room.name}</strong><small>{room.site}</small></span>{checked&&<Check size={22} aria-hidden="true"/>}</label>
     {checked&&<div className="label-room-edit"><label className="field"><span>Texto de la etiqueta de {room.name}</span><textarea rows={2} maxLength={120} readOnly={readOnly} value={text} onChange={e=>setDrafts(previous=>({...previous,[room.id]:e.target.value}))}/></label>{!readOnly&&changed&&<button className="button secondary" disabled={!!busy||!!room.conflict||!text.trim()} onClick={()=>void saveText(room)}>Guardar texto de {room.name}</button>}{room.conflict&&<p className="auth-error">Resuelve los cambios del espacio antes de guardar otro texto.</p>}
      <fieldset className="label-quantities"><legend>Cuántas etiquetas necesitas</legend>{printItems(room).map(item=><label className="label-quantity" key={item.id}><span>{item.name}</span><input type="number" min={0} max={1000} step={1} aria-label={'Etiquetas de '+item.name+' de '+room.name} value={amount(room,item.id)} onChange={e=>{const value=e.target.valueAsNumber;setQuantities(previous=>({...previous,[room.id+':'+item.id]:Number.isFinite(value)?Math.min(1000,Math.max(0,Math.trunc(value))):0}));}}/></label>)}</fieldset><p className="fine-print">Estas cantidades solo sirven para imprimir; no cambian el inventario.</p>{!!room.items.length&&<button className="text-button" onClick={()=>setQuantities(previous=>({...previous,...Object.fromEntries(room.items.map(item=>[room.id+':'+item.id,item.reception??0]))}))}>Usar cantidades de recepción</button>}
     </div>}
    </section>;
   })}{!rooms.length&&<p>Añade un espacio para preparar sus etiquetas.</p>}</div>
   {!!selectedRooms.length&&rooms.some(r=>!selected.includes(r.id))&&<details className="labels-add-spaces" open={search?true:undefined}><summary>Añadir otros espacios<ChevronDown size={20}/></summary><div>{rooms.filter(r=>!selected.includes(r.id)&&matches(r)).map(room=><label className="label-room-choice" key={room.id}><input type="checkbox" checked={false} onChange={()=>toggle(room.id)}/><span><strong>{room.name}</strong><small>{room.site}</small></span></label>)}</div></details>}
  </section></div>
  <aside className="labels-output"><section className="panel"><h2>Tamaño del papelito</h2><div className="label-sizes" role="group" aria-label="Tamaño de etiqueta">{(Object.entries(LABEL_SIZES) as [LabelSize,(typeof LABEL_SIZES)[LabelSize]][]).map(([id,size])=><button type="button" key={id} aria-pressed={options.size===id} onClick={()=>setOptions(o=>({...o,size:id,fontSize:size.fontSize}))}><strong>{size.name}</strong><span>{size.width} × {size.height} mm</span></button>)}</div><p className="fine-print">Pequeña: para pegar debajo de sillas y mesas.</p>
   <div className="label-preview-stage"><div ref={preview} className="label-preview" style={{width:layout.width+'mm',height:layout.height+'mm',fontSize:options.fontSize+'pt',border:options.border?'1px solid #9b9b9b':'1px dashed #9b9b9b'}}><span ref={previewContent}>{previewText}</span></div></div><p className="fine-print">Vista previa orientativa. El PDF conserva las medidas indicadas y ajusta el texto para que quepa.</p>
   <details className="label-customize"><summary>Personalizar impresión<ChevronDown size={20}/></summary><label className="field"><span>Hoja de impresión</span><select value={options.paper} onChange={e=>setOptions(o=>({...o,paper:e.target.value as 'a4'|'letter'}))}><option value="a4">A4 · 210 × 297 mm</option><option value="letter">Carta · 216 × 279 mm</option></select></label><label className="field"><span>Tamaño de letra</span><select value={options.fontSize} onChange={e=>setOptions(o=>({...o,fontSize:Number(e.target.value)}))}>{[10,12,14,18,24].map(n=><option key={n} value={n}>{n} puntos</option>)}</select></label>{([{key:'includeItem',text:'Añadir el nombre del elemento (Sillas, Mesas…)'},{key:'numbered',text:'Numerar los papeles de cada espacio'},{key:'border',text:'Bordes para recortar'}] as const).map(({key,text})=><label className="label-check" key={key}><input type="checkbox" checked={options[key]} onChange={e=>setOptions(o=>({...o,[key]:e.target.checked}))}/><span>{text}</span></label>)}</details>
  </section><section className="panel labels-print-actions"><h2>{total} {total===1?'etiqueta':'etiquetas'}</h2><p>{total?pages+' '+(pages===1?'hoja':'hojas')+' · '+layout.perPage+' etiquetas por hoja':'Selecciona un espacio e indica las cantidades.'}</p>{(error||validation)&&<p className="auth-error" role="alert">{error||validation}</p>}<button className="button primary" disabled={!!busy||!total||!!validation} onClick={()=>void generate(true)}><Printer size={22}/>{busy==='print'?'Preparando impresión…':'Imprimir'}</button><button className="button secondary" disabled={!!busy||!total||!!validation} onClick={()=>void generate(false)}><Download size={22}/>{busy==='pdf'?'Preparando PDF…':'Descargar PDF'}</button><p className="fine-print">Imprime al 100 % o en tamaño real. Máximo {MAX_LABELS} etiquetas por documento.</p>{readOnly&&<p className="fine-print">Puedes imprimir. El texto guardado del espacio lo cambia el equipo con permiso de edición.</p>}</section></aside></div>
 </main>;
}
