import {useEffect,useState} from 'react';
import {Search,Images,Video,Play,Pencil,Trash2,ArrowLeft,Columns2,CloudCheck,CloudUpload} from 'lucide-react';
import type {Media,LocalRoom,User} from '../lib/model';
import {phaseTitle,dateLabel} from '../lib/model';
import {backupLabel,sortedEvidence} from '../lib/evidence';
import {canEditMedia} from './media-viewer';
import {EvidencePreview} from './evidence-preview';
import './evidence.css';
export type GalleryProps={simple?:boolean;media:Media[];user:User;busy?:boolean;onOpen:(media:Media,tool?:'photo'|'details')=>void;onRemove:(media:Media)=>void};
export function MediaAlbum({media,user,busy,onOpen,onRemove,simple=false}:GalleryProps){
 const [search,setSearch]=useState(''),[kind,setKind]=useState('all'),[category,setCategory]=useState('all'),[order,setOrder]=useState('oldest'),[view,setView]=useState('large'),[limit,setLimit]=useState(12);
 useEffect(()=>{setLimit(12);},[search,kind,category,order,media[0]?.roomId]);
 const matches=sortedEvidence(media.filter(m=>!m.deleted&&(kind==='all'||m.mime.startsWith(kind+'/'))&&(category==='all'||m.category===category)&&[m.name,m.note,m.author].join(' ').toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es'))),order),shown=matches.slice(0,limit),categories=[...new Set(media.map(m=>m.category))].sort();
 const controls=<><div className="album-toolbar"><label className="search-field"><Search size={22}/><input aria-label="Buscar fotos y videos" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, nota o persona"/></label><div className="album-view-switch" aria-label="Tamaño de las fotos"><button className="button secondary" aria-pressed={view==='large'} onClick={()=>setView('large')}>Grandes</button><button className="button secondary" aria-pressed={view==='compact'} onClick={()=>setView('compact')}>Compactas</button></div></div><details className="compact-tools album-filters"><summary>Filtrar y ordenar · {matches.length} archivos</summary><div className="album-filter-fields"><label className="field"><span>Tipo de archivo</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Fotos y videos</option><option value="image">Solo fotos</option><option value="video">Solo videos</option></select></label><label className="field"><span>Categoría</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas las categorías</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field"><span>Orden</span><select value={order} onChange={e=>setOrder(e.target.value)}><option value="oldest">Primero las más antiguas</option><option value="newest">Primero las más recientes</option></select></label></div></details></>;
 return <div className="media-album">{media.length>0&&(simple?<details className="album-organize"><summary>Buscar y ordenar archivos</summary>{controls}</details>:controls)}
 <div className={'evidence-grid '+view}>{shown.map(m=><article className="evidence-card" key={m.id}><div className="evidence-image-area"><EvidencePreview media={m}/><button className="evidence-open" aria-label={'Abrir '+m.name} onClick={()=>onOpen(m)}><span className="evidence-kind">{m.mime.startsWith('video/')?<><Play size={19}/>Video{m.duration?' · '+Math.floor(m.duration/60)+':'+String(Math.floor(m.duration%60)).padStart(2,'0'):''}</>:<><Images size={18}/>Ver foto</>}</span></button></div><div className="evidence-caption"><strong>{m.name}</strong><span className="evidence-context">{phaseTitle(m.phase)} · {m.category}</span>{m.note&&<p className="evidence-note">{m.note}</p>}<span className="evidence-author">{m.author} · {dateLabel(m.createdAt)}</span><span className={'evidence-backup '+(m.status==='ready'&&!m.metaDirty?'ready':'pending')}>{m.status==='ready'&&!m.metaDirty?<CloudCheck size={20}/>:<CloudUpload size={20}/>} {backupLabel(m)}</span>{canEditMedia(m,user)&&<div className="evidence-actions"><button className="button secondary" disabled={busy} aria-label={'Editar '+m.name} onClick={()=>onOpen(m,m.mime.startsWith('image/')?'photo':'details')}><Pencil size={20}/>Editar</button><button className="button secondary danger-button" disabled={busy} aria-label={'Quitar '+m.name} onClick={()=>onRemove(m)}><Trash2 size={20}/>Quitar</button></div>}</div></article>)}</div>
 {!matches.length&&(!simple||media.length>0)&&<p className="subtle spaced">{media.length?'No hay archivos que coincidan con estos filtros.':'Todavía no hay fotos ni videos en esta etapa.'}</p>}{matches.length>limit&&<button className="button secondary spaced" onClick={()=>setLimit(n=>n+12)}>Mostrar más · {matches.length-limit} restantes</button>}</div>;
}
export function EvidenceLibrary({rooms,media,user,busy,onOpen,onRemove,onCompare,roomId,phase,onSelectRoom,onPhase}:{rooms:LocalRoom[];roomId:string|null;phase:"reception"|"return";onSelectRoom:(id:string|null)=>void;onPhase:(phase:"reception"|"return")=>void;onCompare:(roomId:string)=>void}&GalleryProps){
 const [search,setSearch]=useState('');const room=rooms.find(r=>r.id===roomId),active=rooms.filter(r=>!r.archived),assets=media.filter(m=>m.roomId===roomId);
 return <div className="evidence-library"><div className="album-toolbar"><label className="field album-room-select"><span>Álbum del espacio</span><select aria-label="Álbum del espacio" value={roomId??''} onChange={e=>onSelectRoom(e.target.value||null)}><option value="">Todos los espacios</option>{active.map(r=><option key={r.id} value={r.id}>{r.site} / {r.name}</option>)}</select></label>{room&&<button className="button secondary" onClick={()=>onSelectRoom(null)}><ArrowLeft size={22}/>Ver álbumes</button>}</div>{!room?<><label className="search-field"><Search size={22}/><input aria-label="Buscar álbum" placeholder="Buscar sala, baño, gimnasio…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="room-albums">{active.filter(r=>[r.name,r.site,r.sector].join(' ').toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es'))).map(r=>{const list=sortedEvidence(media.filter(m=>m.roomId===r.id&&!m.deleted));return <article key={r.id} className="room-album"><div className="album-cover">{list[0]?<EvidencePreview media={list[0]}/>:<Images size={42}/>}</div><button className="room-album-open" aria-label={'Abrir álbum de '+r.name} onClick={()=>onSelectRoom(r.id)}><strong>{r.name}</strong><span>{r.site} · {list.filter(m=>m.mime.startsWith('image/')).length} fotos · {list.filter(m=>m.mime.startsWith('video/')).length} videos</span><span>Recepción {list.filter(m=>m.phase==='reception').length} · Devolución {list.filter(m=>m.phase==='return').length}</span></button></article>;})}</div></>:<><div className="panel-title spaced"><h2>{room.name}</h2><button className="button secondary" onClick={()=>onCompare(room.id)}><Columns2 size={22}/>Comparar</button></div><div className="album-stages"><button className="button secondary" aria-pressed={phase==='reception'} onClick={()=>onPhase('reception')}>Recepción</button><button className="button secondary" aria-pressed={phase==='return'} onClick={()=>onPhase('return')}>Devolución</button></div><MediaAlbum key={room.id+phase} media={assets.filter(m=>m.phase===phase)} user={user} busy={busy} onOpen={onOpen} onRemove={onRemove}/></>}</div>;
}
