import {useEffect,useRef,useState} from 'react';
import {RotateCcw,RotateCw,Check,Undo2} from 'lucide-react';

export function PhotoEditor({src,onSave,onCancel}:{src:string;onSave:(blob:Blob)=>Promise<void>;onCancel:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),[original,setOriginal]=useState<HTMLImageElement|null>(null),[turn,setTurn]=useState(0),[ratio,setRatio]=useState('original'),[zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let disposed=false;const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{if(!disposed)setOriginal(img);};img.onerror=()=>{if(!disposed)setError('No se pudo abrir este formato para editar. El original se conserva y puedes descargarlo.');};img.src=src;return()=>{disposed=true;};},[src]);
 useEffect(()=>{if(!original||!canvas.current)return;const scale=Math.min(1,2048/Math.max(original.naturalWidth,original.naturalHeight)),w=Math.round(original.naturalWidth*scale),h=Math.round(original.naturalHeight*scale);const rotated=document.createElement('canvas');rotated.width=turn%2?h:w;rotated.height=turn%2?w:h;const c=rotated.getContext('2d');if(!c)return;c.translate(rotated.width/2,rotated.height/2);c.rotate(turn*Math.PI/2);c.drawImage(original,-w/2,-h/2,w,h);
 const aspect=ratio==='square'?1:ratio==='landscape'?4/3:ratio==='portrait'?3/4:rotated.width/rotated.height;let cw=rotated.width,ch=cw/aspect;if(ch>rotated.height){ch=rotated.height;cw=ch*aspect;}cw/=zoom;ch/=zoom;const left=(rotated.width-cw)*x/100,top=(rotated.height-ch)*y/100;const output=canvas.current;output.width=Math.max(1,Math.round(cw));output.height=Math.max(1,Math.round(ch));const ctx=output.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,output.width,output.height);ctx.drawImage(rotated,left,top,cw,ch,0,0,output.width,output.height);
 },[original,turn,ratio,zoom,x,y]);
 return <section className="photo-editor"><h3>Recortar o girar foto</h3><p className="subtle">Se guardará una copia. La foto original se conserva.</p>{error?<p role="alert" className="auth-error">{error}</p>:<canvas ref={canvas} aria-label="Vista previa de la foto editada"/>}<div className="actions"><button className="button secondary" disabled={!original||busy} onClick={()=>setTurn(t=>(t+3)%4)}><RotateCcw size={22}/>Girar izquierda</button><button className="button secondary" disabled={!original||busy} onClick={()=>setTurn(t=>(t+1)%4)}><RotateCw size={22}/>Girar derecha</button></div>
 <label className="field"><span>Recorte</span><select aria-label="Forma del recorte" disabled={busy} value={ratio} onChange={e=>setRatio(e.target.value)}><option value="original">Sin cambiar proporción</option><option value="square">Cuadrado</option><option value="landscape">Horizontal</option><option value="portrait">Vertical</option></select></label><label className="field"><span>Acercar imagen · {zoom.toFixed(1)}×</span><input type="range" min={1} max={3} step={.1} aria-label="Acercar imagen" value={zoom} disabled={busy} onChange={e=>setZoom(Number(e.target.value))}/></label>{(zoom>1||ratio!=='original')&&<><label className="field"><span>Mover recorte hacia los lados</span><input type="range" min={0} max={100} step={1} value={x} disabled={busy} onChange={e=>setX(Number(e.target.value))}/></label><label className="field"><span>Mover recorte arriba o abajo</span><input type="range" min={0} max={100} step={1} value={y} disabled={busy} onChange={e=>setY(Number(e.target.value))}/></label></>}
 <div className="actions"><button className="button primary" disabled={!original||!!error||busy} onClick={async()=>{setBusy(true);setError('');try{const blob=await new Promise<Blob>((resolve,reject)=>canvas.current?.toBlob(b=>b?resolve(b):reject(new Error('No se pudo preparar la copia.')),'image/jpeg',.92));await onSave(blob);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Check size={22}/>{busy?'Guardando…':'Guardar copia editada'}</button><button className="button secondary" disabled={busy} onClick={()=>{setTurn(0);setRatio('original');setZoom(1);setX(50);setY(50);}}><Undo2 size={22}/>Restablecer</button><button className="text-button" disabled={busy} onClick={onCancel}>Cancelar edición</button></div></section>;
}
