import type {Media,Room} from '../lib/model';
import {phaseTitle} from '../lib/model';
import {comparisonPairs,sortedEvidence} from '../lib/evidence';
import {reportEvidence,type PdfEvidenceOptions} from '../lib/report-options';
import type {ReportKind} from '../lib/reports';
import {EvidencePreview} from './evidence-preview';
import './evidence.css';
export function ReportEvidenceOptions({rooms,media,kind,options,onChange}:{rooms:Room[];media:Media[];kind:ReportKind;options:PdfEvidenceOptions;onChange:(options:PdfEvidenceOptions)=>void}){
 const photos=sortedEvidence(media.filter(m=>!m.deleted&&m.mime.startsWith('image/')&&(kind==='comparison'||m.phase===kind))),pairs=comparisonPairs(media),chosen=reportEvidence(media,kind,options);
 const roomName=(id:string)=>rooms.find(r=>r.id===id)?.name??'Espacio';
 function toggle(field:'selectedPhotoIds'|'selectedComparisonIds',id:string,all:string[]){const ids=options[field]??all;onChange({...options,[field]:ids.includes(id)?ids.filter(value=>value!==id):[...ids,id]});}
 return <section className="report-evidence-options" aria-label="Imágenes del PDF"><h3>Imágenes del PDF</h3><p className="fine-print">Elige qué mostrar en esta descarga. El registro y los archivos originales se conservan completos.</p>
 <label className="check-label"><input type="checkbox" checked={options.includePhotos} onChange={e=>onChange({...options,includePhotos:e.target.checked})}/>Incluir fotos individuales</label>
 {options.includePhotos&&<details className="compact-tools"><summary>Elegir fotos · {chosen.photos.length} de {photos.length}</summary><div className="report-selection-actions"><button className="button secondary" onClick={()=>onChange({...options,selectedPhotoIds:undefined})}>Todas las fotos</button><button className="button secondary" onClick={()=>onChange({...options,selectedPhotoIds:[]})}>Ninguna foto</button></div><div className="report-selection-list">{photos.map(m=><div className="report-selection-item" key={m.id}><input id={'report-photo-'+m.id} type="checkbox" aria-label={'Incluir foto '+m.name} checked={!options.selectedPhotoIds||options.selectedPhotoIds.includes(m.id)} onChange={()=>toggle('selectedPhotoIds',m.id,photos.map(p=>p.id))}/><span><label htmlFor={'report-photo-'+m.id}><strong>{m.name}</strong><small>{roomName(m.roomId)} · {phaseTitle(m.phase)}</small></label><div className="report-selection-previews"><EvidencePreview media={m}/></div></span></div>)}</div>{!photos.length&&<p className="subtle">No hay fotos en los espacios y etapas elegidos.</p>}</details>}
 {kind==='comparison'&&<><label className="check-label"><input type="checkbox" checked={options.includeComparison} onChange={e=>onChange({...options,includeComparison:e.target.checked})}/>Incluir comparación visual</label>{options.includeComparison&&<details className="compact-tools" open><summary>Elegir parejas · {chosen.pairs.length} de {pairs.length}</summary><p className="fine-print">Vincula las fotos desde «Comparar» en cada espacio. Aquí eliges qué parejas entregar.</p><div className="report-selection-actions"><button className="button secondary" onClick={()=>onChange({...options,selectedComparisonIds:undefined})}>Todas las parejas</button><button className="button secondary" onClick={()=>onChange({...options,selectedComparisonIds:[]})}>Ninguna pareja</button></div><div className="report-selection-list">{pairs.map(({reception,returned})=><div className="report-selection-item" key={returned.id}><input id={'report-pair-'+returned.id} type="checkbox" aria-label={'Incluir pareja '+reception.name+' y '+returned.name} checked={!options.selectedComparisonIds||options.selectedComparisonIds.includes(returned.id)} onChange={()=>toggle('selectedComparisonIds',returned.id,pairs.map(p=>p.returned.id))}/><span><label htmlFor={'report-pair-'+returned.id}><strong>{roomName(returned.roomId)}</strong><small>Recepción: {reception.name}</small><small>Devolución: {returned.name}</small></label><div className="report-selection-previews"><EvidencePreview media={reception}/><EvidencePreview media={returned}/></div></span></div>)}</div>{!pairs.length&&<p className="subtle">Todavía no hay parejas guardadas para estos espacios.</p>}</details>}</>}
 <p className="fine-print" role="status">Esta descarga: {chosen.photos.length} foto(s) individual(es) y {chosen.pairs.length} pareja(s). Los videos figuran en el índice y se entregan como originales.</p></section>;
}
