import {useRef,useState,useEffect} from 'react';
import {ZoomIn,ZoomOut,RotateCcw} from 'lucide-react';
type Point={x:number;y:number};
export function ZoomImage({src,alt,onError,onLoad,onPrevious,onNext}:{src:string;alt:string;onError:()=>void;onLoad?:()=>void;onPrevious?:()=>void;onNext?:()=>void}){
 const surface=useRef<HTMLDivElement>(null),img=useRef<HTMLImageElement>(null),points=useRef(new Map<number,Point>()),gesture=useRef({start:{x:0,y:0},pan:{x:0,y:0},distance:0,scale:1,pinched:false,time:0}),lastTap=useRef(0);
 const [scale,setScale]=useState(1),[pan,setPan]=useState({x:0,y:0});
 useEffect(()=>{setScale(1);setPan({x:0,y:0});points.current.clear();},[src]);
 function clamp(point:Point,z:number){const box=surface.current,image=img.current;if(!box||!image?.naturalWidth)return {x:0,y:0};const fit=Math.min(box.clientWidth/image.naturalWidth,box.clientHeight/image.naturalHeight);const maxX=Math.max(0,(image.naturalWidth*fit*z-box.clientWidth)/2),maxY=Math.max(0,(image.naturalHeight*fit*z-box.clientHeight)/2);return {x:Math.max(-maxX,Math.min(maxX,point.x)),y:Math.max(-maxY,Math.min(maxY,point.y))};}
 function zoom(value:number){const next=Math.max(1,Math.min(5,value));setScale(next);setPan(p=>clamp(p,next));}
 return <div className="zoom-photo"><div className="zoom-controls"><button className="button secondary" aria-label="Alejar foto" disabled={scale<=1} onClick={()=>zoom(scale-.5)}><ZoomOut size={22}/></button><span aria-live="polite">{Math.round(scale*100)}%</span><button className="button secondary" aria-label="Ampliar foto" disabled={scale>=5} onClick={()=>zoom(scale+.5)}><ZoomIn size={22}/></button><button className="button secondary" onClick={()=>{setScale(1);setPan({x:0,y:0});}}><RotateCcw size={20}/>Ajustar</button></div><div className="zoom-surface" ref={surface} onDoubleClick={()=>zoom(scale===1?2:1)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.current.size===1)gesture.current={start:{x:e.clientX,y:e.clientY},pan,scale,distance:0,pinched:false,time:Date.now()};if(points.current.size===2){const [a,b]=[...points.current.values()];gesture.current={...gesture.current,distance:Math.hypot(a.x-b.x,a.y-b.y),scale,pinched:true};}}} onPointerMove={e=>{if(!points.current.has(e.pointerId))return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture.current;if(points.current.size===2&&g.distance){const [a,b]=[...points.current.values()];zoom(g.scale*Math.hypot(a.x-b.x,a.y-b.y)/g.distance);}else if(points.current.size===1&&scale>1&&!g.pinched){setPan(clamp({x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y},scale));}}} onPointerUp={e=>{const g=gesture.current;points.current.delete(e.pointerId);if(points.current.size||g.pinched)return;const dx=e.clientX-g.start.x,dy=e.clientY-g.start.y;if(scale===1&&Math.abs(dx)>65&&Math.abs(dy)<55&&Date.now()-g.time<1000){if(dx>0)onPrevious?.();else onNext?.();}else if(e.pointerType==='touch'&&Math.abs(dx)<12&&Math.abs(dy)<12){if(Date.now()-lastTap.current<280){zoom(scale===1?2:1);lastTap.current=0;}else lastTap.current=Date.now();}}} onPointerCancel={e=>{points.current.delete(e.pointerId);}}><img ref={img} src={src} alt={alt} draggable={false} onLoad={onLoad} onError={onError} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${scale})`}}/></div><p className="fine-print">Amplía con dos dedos o con +. Al ampliar puedes arrastrar la foto; al 100% desliza para cambiar de archivo.</p></div>;
}
