import { randomBytes,randomUUID,createHash,scrypt as scryptCallback,timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { existsSync,writeFileSync,readFileSync,unlinkSync } from 'node:fs';
import { resolve } from 'node:path';
import { z } from 'zod';
import { sqlite,DATA_DIR } from './storage';
import type { User } from '../lib/model';
const scrypt=promisify(scryptCallback);
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const cookieName='orden_session';
const setupFile=resolve(DATA_DIR,'setup-key.txt');
function needsSetup(){return !sqlite.prepare('SELECT id FROM members LIMIT 1').get();}
if(needsSetup()&&!existsSync(setupFile))writeFileSync(setupFile,randomBytes(24).toString('base64url'),{mode:0o600,flag:'wx'});
export class AuthError extends Error {constructor(message:string,public status=401){super(message);}}
function tokenOf(request:Request){return request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1)??'';}
export async function identity(request:Request):Promise<User>{const token=tokenOf(request);const user=token&&sqlite.prepare('SELECT m.id,m.name,m.email,m.role FROM sessions s JOIN members m ON m.id=s.user_id JOIN credentials c ON c.user_id=m.id WHERE s.token_hash=? AND s.expires_at>? AND c.disabled=0').get(sha(token),Date.now());if(!user)throw new AuthError('Ingresa con tu usuario para continuar.');return user as unknown as User;}
function sessionResponse(request:Request,userId:string){const token=randomBytes(32).toString('base64url');sqlite.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now());sqlite.prepare('INSERT INTO sessions VALUES (?,?,?)').run(sha(token),userId,Date.now()+30*86400000);return Response.json({ok:true},{headers:{'Set-Cookie':`${cookieName}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${new URL(request.url).protocol==='https:'?'; Secure':''}`,'Cache-Control':'no-store'}});}
async function passwordHash(password:string){const salt=randomBytes(16).toString('hex');const hash=await scrypt(password,salt,64) as Buffer;return salt+':'+hash.toString('hex');}
async function checkPassword(password:string,stored:string){const [salt,hex]=stored.split(':');const expected=Buffer.from(hex,'hex');const result=await scrypt(password,salt,64) as Buffer;return expected.length===result.length&&timingSafeEqual(result,expected);}
const account=z.object({name:z.string().trim().min(2).max(100),username:z.string().trim().toLowerCase().regex(/^[a-z0-9._-]{3,40}$/),password:z.string().min(12).max(200)});
const attempts=new Map<string,{count:number,until:number}>();
function throttle(key:string){const now=Date.now();for(const [k,v] of attempts)if(v.until<now)attempts.delete(k);const current=attempts.get(key)??{count:0,until:now+15*60000};current.count++;attempts.set(key,current);if(current.count>20)throw new AuthError('Demasiados intentos. Espera 15 minutos antes de volver a intentar.',429);}
function addAccount(data:z.infer<typeof account>,hash:string,role:string){const id=randomUUID();sqlite.prepare('INSERT INTO members VALUES (?,?,?,?)').run(id,data.username,data.name,role);sqlite.prepare('INSERT INTO credentials(user_id,username,password_hash) VALUES (?,?,?)').run(id,data.username,hash);return id;}
export async function handleAuth(request:Request):Promise<Response|null>{const path=new URL(request.url).pathname;if(!path.startsWith('/api/auth/'))return null;try{
 if(request.method==='GET'&&path==='/api/auth/status')return Response.json({needsSetup:needsSetup()},{headers:{'Cache-Control':'no-store'}});
 if(request.method!=='POST')throw new AuthError('Método no permitido.',405);
 if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)throw new AuthError('Origen no permitido.',403);
 const data=await request.json();
 if(path==='/api/auth/setup'){throttle('setup');if(!needsSetup())throw new AuthError('La aplicación ya tiene coordinador.',409);const input=account.extend({setupKey:z.string().min(20).max(100)}).parse(data);const actual=readFileSync(setupFile,'utf8').trim();if(sha(input.setupKey)!==sha(actual))throw new AuthError('La clave de instalación no es correcta.',403);const hash=await passwordHash(input.password);sqlite.exec('BEGIN IMMEDIATE');let id;try{if(!needsSetup())throw new AuthError('La aplicación ya tiene coordinador.',409);id=addAccount(input,hash,'coordinator');sqlite.exec('COMMIT');}catch(e){sqlite.exec('ROLLBACK');throw e;}unlinkSync(setupFile);return sessionResponse(request,id);}
 if(path==='/api/auth/login'){const input=z.object({username:z.string().trim().toLowerCase().max(100),password:z.string().max(200)}).parse(data);throttle('login:'+input.username);throttle('global-login');const row=sqlite.prepare('SELECT * FROM credentials WHERE username=? AND disabled=0').get(input.username);const valid=await checkPassword(input.password,String(row?.password_hash??'00000000000000000000000000000000:'.padEnd(161,'0')));if(!row||!valid)throw new AuthError('Usuario o contraseña incorrectos.');attempts.delete('login:'+input.username);attempts.delete('global-login');return sessionResponse(request,String(row.user_id));}
 if(path==='/api/auth/logout'){sqlite.prepare('DELETE FROM sessions WHERE token_hash=?').run(sha(tokenOf(request)));return Response.json({ok:true},{headers:{'Set-Cookie':`${cookieName}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`}});}
 if(path==='/api/auth/invites'){const user=await identity(request);if(user.role!=='coordinator')throw new AuthError('Solo el coordinador puede crear accesos.',403);const input=z.object({name:z.string().trim().min(2).max(100)}).parse(data);const code=randomBytes(24).toString('base64url');const expiresAt=Date.now()+48*3600000;sqlite.prepare('INSERT INTO invites VALUES (?,?,?,NULL)').run(sha(code),input.name,expiresAt);return Response.json({code,expiresAt,name:input.name});}
 if(path==='/api/auth/join'){throttle('join');const input=account.extend({code:z.string().min(20).max(100)}).parse(data);const hash=await passwordHash(input.password);sqlite.exec('BEGIN IMMEDIATE');let id;try{const invite=sqlite.prepare('SELECT * FROM invites WHERE code_hash=? AND used_at IS NULL AND expires_at>?').get(sha(input.code),Date.now());if(!invite)throw new AuthError('El acceso expiró o ya fue utilizado.',403);id=addAccount(input,hash,'recorder');sqlite.prepare('UPDATE invites SET used_at=? WHERE code_hash=?').run(Date.now(),sha(input.code));sqlite.exec('COMMIT');}catch(e){sqlite.exec('ROLLBACK');throw e;}return sessionResponse(request,id);}
 if(path==='/api/auth/revoke'){const user=await identity(request);if(user.role!=='coordinator')throw new AuthError('Solo el coordinador puede quitar accesos.',403);const {userId}=z.object({userId:z.string().uuid()}).parse(data);if(user.id===userId)throw new AuthError('No puedes desactivar tu propio acceso.',400);sqlite.prepare('UPDATE credentials SET disabled=1 WHERE user_id=?').run(userId);sqlite.prepare('DELETE FROM sessions WHERE user_id=?').run(userId);return Response.json({ok:true});}
 throw new AuthError('Acción no encontrada.',404);
 }catch(e){if(e instanceof AuthError)return Response.json({error:e.message},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:e.issues.map(i=>i.path.join('.')+': '+i.message).join('; ')},{status:400});if(String(e).includes('UNIQUE'))return Response.json({error:'Ese nombre de usuario ya existe.'},{status:409});console.error('Acceso',e);return Response.json({error:'No se pudo completar el acceso.'},{status:500});}}
