export type AuditEntry={id:number;created_at:string;category:string;action:string;entity_id:string;entity_name:string;actor_id:string|null;actor_name:string;before_data:Record<string,unknown>|null;after_data:Record<string,unknown>|null;legacy:boolean};
export const AUDIT_CATEGORIES:Record<string,string>={spaces:'Espacios e inventario',files:'Fotos y videos',team:'Equipo y permisos',event:'Datos del evento',reports:'Informes'};
export const AUDIT_ACTIONS:Record<string,string>={created:'Creación',updated:'Edición',deleted:'Eliminación',revision:'Revisión anterior',trashed:'Enviado a papelera',restored:'Restauración',uploaded:'Archivo respaldado',disabled:'Acceso desactivado',reactivated:'Acceso reactivado',role:'Cambio de rol',archived:'Espacio archivado'};
const labels:Record<string,string>={name:'Nombre',site:'Recinto',type:'Tipo',sector:'Sector',responsible:'Encargado',archived:'Archivado',notes:'Observaciones',note:'Nota',category:'Categoría',deleted:'En papelera',role:'Rol',disabled:'Desactivado',email:'Correo',institution:'Organización',location:'Lugar',coordinator:'Coordinador',title:'Título',kind:'Contenido',phase:'Etapa',status:'Respaldo',confirmedAt:'Confirmación',confirmedBy:'Confirmado por',derivedFrom:'Original de la copia',comparisonId:'Foto de recepción vinculada'};
const values:Record<string,string>={admin:'Administrador',coordinator:'Coordinador',recorder:'Encargado',viewer:'Solo lectura',pending:'Pendiente',ready:'Respaldado',ok:'Bien',issue:'Observación',na:'No aplica',reception:'Recepción',return:'Devolución',comparison:'Recepción y devolución'};
function text(value:unknown):string{if(value===null||value===undefined||value==='')return 'Sin registrar';if(typeof value==='boolean')return value?'Sí':'No';return values[String(value)]??String(value);}
function flatten(data:Record<string,unknown>|null){const out:Record<string,string>={};if(!data)return out;
 for(const [key,value] of Object.entries(data)){
  if(['id','roomId','createdAt','updatedAt','updatedBy','revision','mutationId','author','ownerId','thumbnailReady','mime','size','duration','roomIds'].includes(key))continue;
  if(key==='items'&&Array.isArray(value)){for(const item of value){if(!item||typeof item!=='object')continue;const i=item as Record<string,unknown>;out['Inventario / '+i.name+' / Recepción']=text(i.reception);out['Inventario / '+i.name+' / Devolución']=text(i.return);}continue;}
  if((key==='reception'||key==='return')&&value&&typeof value==='object'){const stage=value as Record<string,unknown>;for(const [field,val] of Object.entries(stage)){if(field==='checks'&&val&&typeof val==='object'){for(const [name,state] of Object.entries(val))out[values[key]+' / '+name]=text(state);}else out[values[key]+' / '+(labels[field]??field)]=text(val);}continue;}
  if(value===null||typeof value!=='object')out[labels[key]??key]=text(value);
 }
 return out;
}
export function auditChanges(entry:AuditEntry){const before=flatten(entry.before_data),after=flatten(entry.after_data);return [...new Set([...Object.keys(before),...Object.keys(after)])].filter(key=>before[key]!==after[key]).map(field=>({field,before:before[field]??'No existía',after:after[field]??'Quitado'}));}
export function auditContext(entry:AuditEntry,roomNames:Record<string,string>={}){const data=entry.after_data??entry.before_data;const roomId=data?.roomId;return {room:typeof roomId==='string'?(roomNames[roomId]??roomId):entry.category==='spaces'?entry.entity_name:'',phase:typeof data?.phase==='string'?(values[data.phase]??data.phase):''};}
export function auditCsv(entries:AuditEntry[],roomNames:Record<string,string>={}){const cell=(s:string)=>'"'+(/^[=+\-@\t\r]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';return '\uFEFF'+[['Fecha','Persona','Categoría','Acción','Registro','Espacio','Etapa','Cambios','Historial anterior'],...entries.map(e=>[e.created_at,e.actor_name,AUDIT_CATEGORIES[e.category]??e.category,AUDIT_ACTIONS[e.action]??e.action,e.entity_name,auditContext(e,roomNames).room,auditContext(e,roomNames).phase,auditChanges(e).map(c=>`${c.field}: ${c.before} → ${c.after}`).join('\n'),e.legacy?'Sí':'No'])].map(row=>row.map(cell).join(';')).join('\r\n');}
