import type {LocalRoom,Media,User,Room,EventInfo} from './model';
let connection:Promise<IDBDatabase>|null=null;
let activeId='';
function request<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function finished(tx:IDBTransaction){return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??new Error('No se pudo guardar en este teléfono.'));});}
export function localIdentity():User|null {try{return JSON.parse(localStorage.getItem('orden-last-user')??'null');}catch{return null;}}
export function activateLocal(user:User){if(activeId!==user.id){connection?.then(db=>db.close());connection=null;activeId=user.id;}localStorage.setItem('orden-last-user',JSON.stringify(user));}
function open(){if(!activeId)throw new Error('Primero conecta tu cuenta.');if(!connection)connection=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('orden-colegio-v1-'+activeId,1);r.onupgradeneeded=()=>{const db=r.result;db.createObjectStore('rooms',{keyPath:'id'});db.createObjectStore('media',{keyPath:'id'});db.createObjectStore('files');db.createObjectStore('meta');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{connection=null;reject(r.error);};r.onblocked=()=>reject(new Error('Cierra otras pestañas de la app e intenta de nuevo.'));});return connection;}
export async function allRooms(){const db=await open();return request(db.transaction('rooms').objectStore('rooms').getAll()) as Promise<LocalRoom[]>;}
export async function allMedia(){const db=await open();return request(db.transaction('media').objectStore('media').getAll()) as Promise<Media[]>;}
export async function getRoomLocal(id:string){const db=await open();return request(db.transaction('rooms').objectStore('rooms').get(id)) as Promise<LocalRoom|undefined>;}
export async function putRoom(room:LocalRoom){const db=await open();const tx=db.transaction('rooms','readwrite');tx.objectStore('rooms').put(room);await finished(tx);}
export async function putRooms(rooms:LocalRoom[]){const db=await open();const tx=db.transaction('rooms','readwrite');rooms.forEach(r=>tx.objectStore('rooms').put(r));await finished(tx);}
export async function putMedia(media:Media){const db=await open();const tx=db.transaction('media','readwrite');const {blob,thumbnail,...meta}=media;void blob;void thumbnail;tx.objectStore('media').put(meta);await finished(tx);}
export async function patchMedia(id:string,changes:Partial<Media>){const db=await open();const tx=db.transaction('media','readwrite');const store=tx.objectStore('media');const current=await request(store.get(id)) as Media|undefined;if(current)store.put({...current,...changes});await finished(tx);}
export async function addFile(media:Media,blob:Blob,thumbnail?:Blob){const db=await open();const tx=db.transaction(['media','files'],'readwrite');const {blob:unused,thumbnail:unused2,...meta}=media;void unused;void unused2;tx.objectStore('media').put(meta);tx.objectStore('files').put(blob,media.id);if(thumbnail)tx.objectStore('files').put(thumbnail,media.id+':thumbnail');await finished(tx);}
export async function fileBlob(id:string){const db=await open();return request(db.transaction('files').objectStore('files').get(id)) as Promise<Blob|undefined>;}
export async function cacheFile(id:string,blob:Blob){const db=await open();const tx=db.transaction('files','readwrite');tx.objectStore('files').put(blob,id);await finished(tx);}
export async function setMeta(key:string,value:unknown){const db=await open();const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(value,key);await finished(tx);}
export async function getMeta<T>(key:string){const db=await open();return request(db.transaction('meta').objectStore('meta').get(key)) as Promise<T|undefined>;}
export async function acceptSync(sent:LocalRoom,server:Room){const db=await open();const tx=db.transaction('rooms','readwrite');const store=tx.objectStore('rooms');const current=await request(store.get(sent.id)) as LocalRoom|undefined;if(current){store.put(current.localVersion===sent.localVersion?{...server,dirty:false}:{...current,revision:server.revision});}await finished(tx);}
export async function mergeServer(rooms:Room[],media:Media[]){const db=await open();const tx=db.transaction(['rooms','media'],'readwrite');const rs=tx.objectStore('rooms');const ms=tx.objectStore('media');for(const remote of rooms){const local=await request(rs.get(remote.id)) as LocalRoom|undefined;if(!local||!local.dirty){rs.put({...remote,dirty:false});}else if(remote.revision>local.revision&&remote.mutationId!==local.mutationId){rs.put({...local,conflict:remote});}}for(const remote of media){const local=await request(ms.get(remote.id)) as Media|undefined;ms.put({...local,...remote,...(local?.metaDirty?{note:local.note,category:local.category,metaDirty:true}:{}),status:'ready'});}await finished(tx);}
export async function storageEstimate(){return navigator.storage?.estimate?navigator.storage.estimate():{};}
export async function requestPersistence(){return navigator.storage?.persist? navigator.storage.persist():false;}
export type Bootstrap={user:User;rooms:Room[];media:Media[];team:User[];event:EventInfo};
